categories = ['Revenue per share',
              'Earnings per share',
              'FCF per share',
              'Book Value per sh.',
              'Dividends per share',
              'CAPEX per share',
              'Comm.Shares outs.',
              'Avg. annual P/E ratio',
              'P/E to S&P500',
              'Avg. annual div. yield',
              'Revenue',
              'Operating margin',
              'Depreciation',
              'Net profit',
              'Income tax rate',
              'Net profit margin',
              'Working capital',
              'Long-term debt',
              'Equity',
              'ROIC',
              'Return on capital',
              'Return on equity',
              'Plowback ratio',
              'Div.&Repurch./FCF']

data = {'Revenue per share': [],
        'Earnings per share': [],
        'FCF per share': [],
        'Dividends per share': [],
        'CAPEX per share': [],
        'Book Value per sh.': [],
        'Comm.Shares outs.': [],
        'Avg. annual P/E ratio': [],
        'P/E to S&P500': [],
        'Avg. annual div. yield': [],
        'Revenue': [],
        'Operating margin': [],
        'Depreciation': [],
        'Net profit': [],
        'Income tax rate': [],
        'Net profit margin': [],
        'Working capital': [],
        'Long-term debt': [],
        'Equity': [],
        'ROIC': [],
        'Return on capital': [],
        'Return on equity': [],
        'Plowback ratio': [],
        'Div.&Repurch./FCF': [],
        }

configs = {'stocks': "\nExtract one or two stock symbols from the following and return them as a comma separated string: ",
           'graph': "",
           }
